# Numpy

In [2]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(5,)

In [3]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
list1=[2,3,4,5,6]
arr1=np.asarray(list1)

In [ ]:
arr1

array([2, 3, 4, 5, 6])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
type(list1)

list

In [ ]:
arr1.shape

(5,)

In [ ]:
np.array?

In [ ]:
x=np.array([[1,2,3],[5,6,7],[9,10,11],[13,14,15]])

In [ ]:
x

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
x.shape

(4, 3)

In [ ]:
x[2,1]

10

In [ ]:
x[1,1]

6

In [ ]:
x

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
x[:,1]

array([ 2,  6, 10, 14])

In [ ]:
x[2,:]

array([ 9, 10, 11])

In [ ]:
x[2,1:3]

array([10, 11])

In [ ]:
x[0:2,0:2]

array([[1, 2],
       [5, 6]])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [ ]:
a=np.zeros((4,5))

In [ ]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
b=np.eye(5,5)

In [ ]:
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
c=np.ones((4,5))

In [ ]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
d=np.random.random((3,4))

In [ ]:
d

array([[0.11815172, 0.48433489, 0.26432011, 0.38125194],
       [0.55856722, 0.20831119, 0.20062754, 0.77811077],
       [0.94901276, 0.96331763, 0.71044281, 0.43074394]])

In [ ]:
dt=d.T

In [ ]:
dt

array([[0.11815172, 0.55856722, 0.94901276],
       [0.48433489, 0.20831119, 0.96331763],
       [0.26432011, 0.20062754, 0.71044281],
       [0.38125194, 0.77811077, 0.43074394]])

In [ ]:
dtreshape= d.reshape(12,1)

In [ ]:
dtreshape

array([[0.11815172],
       [0.48433489],
       [0.26432011],
       [0.38125194],
       [0.55856722],
       [0.20831119],
       [0.20062754],
       [0.77811077],
       [0.94901276],
       [0.96331763],
       [0.71044281],
       [0.43074394]])

In [ ]:
dtreshape.shape

(12, 1)

In [ ]:
e=np.arange(5)

In [ ]:
e

array([0, 1, 2, 3, 4])

In [ ]:
 f=np.arange(5)

In [ ]:
add=e+f
sub=e-f
multele=e*f

In [ ]:
add

array([0, 2, 4, 6, 8])

In [ ]:
sub

array([0, 0, 0, 0, 0])

In [ ]:
multele

array([ 0,  1,  4,  9, 16])

In [ ]:
print(e,e+1)

[0 1 2 3 4] [1 2 3 4 5]


In [ ]:
g=np.random.random((2,3))
print(g)

[[0.80222633 0.0705768  0.55284015]
 [0.52215924 0.61312832 0.78651286]]


In [ ]:
print(g+1)

[[1.80222633 1.0705768  1.55284015]
 [1.52215924 1.61312832 1.78651286]]


In [ ]:
np.floor(g*100)

array([[80.,  7., 55.],
       [52., 61., 78.]])

In [ ]:
u=[1,2,3,4,5]
v=[2,36,5,4,7]

In [ ]:
prod=np.inner(u,v)

In [ ]:
prod

140

In [ ]:
prod=np.outer(u,v)

In [ ]:
prod

array([[  2,  36,   5,   4,   7],
       [  4,  72,  10,   8,  14],
       [  6, 108,  15,  12,  21],
       [  8, 144,  20,  16,  28],
       [ 10, 180,  25,  20,  35]])

In [ ]:
h=np.ones((2,3))
i=np.ones((2,3))

In [ ]:
np.dot(h,i.T)

array([[3., 3.],
       [3., 3.]])

In [ ]:
h.sum()

6.0

In [ ]:
prod.sum(axis=0)

array([ 30, 540,  75,  60, 105])

In [ ]:
prod.sum(axis=1)

array([ 54, 108, 162, 216, 270])

In [ ]:
prod.max()

180

In [4]:
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# Create a 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.96856311, 0.52600988, 0.36713026],
       [0.33208502, 0.61562238, 0.96861964],
       [0.63631468, 0.32533876, 0.14630347]])

In [11]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.40439923,  0.24774356,  1.47363604],
       [-0.05822795,  1.17914753,  0.49882228],
       [ 1.02577191,  0.45415808,  0.94617634]])

In [12]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[4, 2, 8],
       [2, 6, 9],
       [9, 2, 4]])

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations.
Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table.
Note that when constructing an array, they can be specified using a string:

```python
np.zeros(10, dtype='int16')
```

Or using the associated NumPy object:

```python
np.zeros(10, dtype=np.int16)
```

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

More advanced type specification is possible, such as specifying big or little endian numbers; for more information, refer to the [NumPy documentation](http://numpy.org/).
NumPy also supports compound data types, which will be covered in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).

