<a href="https://colab.research.google.com/github/ydadwhal/DataScienceDIAT/blob/main/LinearRegression1503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df1=pd.read_csv('insurance.csv')

In [ ]:
df1.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
df1.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df2=df1[['age','bmi','charges']]

In [ ]:
df2.head()

age     bmi      charges
0   19  27.900  16884.92400
1   18  33.770   1725.55230
2   28  33.000   4449.46200
3   33  22.705  21984.47061
4   32  28.880   3866.85520

In [ ]:
X=np.array(df2[['age','bmi']])

In [ ]:
X.shape

(1338, 2)

In [ ]:
y=np.array(df2['charges'])

In [ ]:
y.shape

(1338,)

In [ ]:
X1=np.append(X,np.ones((X.shape[0],1)),axis=1)

In [ ]:
X1.shape

(1338, 3)

In [ ]:
X1[1]

array([18.  , 33.77,  1.  ])

In [ ]:
X2=np.array(np.ones((X.shape[0],1)))

In [ ]:
X3=np.append(X2,X,axis=1)

In [ ]:
X3.shape

(1338, 3)

In [ ]:
X3[0:5]

array([[ 1.   , 19.   , 27.9  ],
       [ 1.   , 18.   , 33.77 ],
       [ 1.   , 28.   , 33.   ],
       [ 1.   , 33.   , 22.705],
       [ 1.   , 32.   , 28.88 ]])

In [ ]:
theta=np.zeros((X3.shape[1],1))

In [ ]:
theta

array([[0.],
       [0.],
       [0.]])

In [ ]:
print(y.shape,X3.shape,theta.shape)

(1338,) (1338, 3) (3, 1)


In [ ]:
y=np.expand_dims(y,axis=1)

In [ ]:
np.linalg.inv(np.transpose(X3))

In [ ]:
marker=10
"marker='{0}'".format(marker)

"marker='10'"